import json
import re

class PlanAnalyzer:
    def __init__(self, pipeline):
        self.pipe = pipeline

    def analyze(self, soap_note: dict, doctor_plan: dict, ethnicity: str = "Not provided"):
        messages = [
            {
                "role": "system",
                "content": [{
                    "type": "text",
                    "text": (
                        """You are Agent 2 in the MedFlow AI system.

Your role:
- Receive the SOAP note (S, O, A) generated by Agent 1.
- Receive the Plan provided by the doctor (medications, tests, follow-up).
- Produce a complete SOAP note including Subjective, Objective, Assessment, and the Plan.
- Analyze the plan for alignment with symptoms and assessment.
- Provide recommendations for lifestyle, food, exercise, clothing, music, and fragrances based on patient context and prescription.
- Highlight missing information or caution if relevant.
- Maintain patient safety and clinical neutrality.
- Do NOT diagnose or prescribe new medications or new tests.

Output format:
- Return valid JSON ONLY.
- Include the following keys:
  1. soap_note: a full SOAP note including Plan
  2. medication_review: alignment score (%) and rationale
  3. test_validation: relevance score (%) and rationale for each test
  4. lifestyle_recommendations: food, exercise, clothing, music, fragrance
  5. additional_notes: optional notes on patient context or missing info
- Percentages should be numbers (0-100)
- Explain reasoning in rationale fields
- Clearly indicate missing or uncertain information

"""
                    )
                }]
            },
            {
                "role": "user",
                "content": [{
                    "type": "text",
                    "text": (
                        "Analyze the following clinical data.\n\n"
                        "Tasks:\n"
                        "1. Evaluate whether the prescribed medicines align with the symptoms and assessment.\n"
                        "2. Evaluate whether the prescribed lab tests are clinically relevant.\n"
                        "3. Provide confidence scores (0–100%) with brief rationales.\n"
                        "4. Suggest lifestyle, food, exercise, clothing, music, and fragrance recommendations.\n\n"
                        "Return ONLY a JSON object.\n\n"
                        f"SOAP Note:\n{json.dumps(soap_note, indent=2)}\n\n"
                        f"Doctor Plan:\n{json.dumps(doctor_plan, indent=2)}\n\n"
                        f"Patient Ethnicity: {ethnicity}"
                    )
                }]
            }
        ]

        output = self.pipe(text=messages, max_new_tokens=2000)
        assistant_text = output[-1]["generated_text"]

        json_text = re.sub(r"```json|```", "", assistant_text[-1]["content"]).strip()

        try:
            return json.loads(json_text)
        except json.JSONDecodeError:
            return {
                "medicine_alignment": {"confidence_score": None, "rationale": "Parsing failed"},
                "lab_test_analysis": [],
                "lifestyle_recommendations": {},
                "missing_information": ["Model output could not be parsed"],
                "safety_notice": "Consult a healthcare professional."
            }
